import type { Metadata } from 'next'
import { Montserrat, Oxanium } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'DevStage App',
  description: 'Generated by create next app',
}

const oxanium = Oxanium({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-oxanium',
})
const montserrat = Montserrat({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-BR' className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className='bg-black text-white font-bold text-4xl'>{children}</body>
    </html>
  )
}
